
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int op_asig = 2;
  public static final int op_resta = 4;
  public static final int const_float = 9;
  public static final int id = 7;
  public static final int const_int = 8;
  public static final int EOF = 0;
  public static final int const_str = 10;
  public static final int op_div = 6;
  public static final int op_suma = 3;
  public static final int error = 1;
  public static final int op_mul = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "op_asig",
  "op_suma",
  "op_resta",
  "op_mul",
  "op_div",
  "id",
  "const_int",
  "const_float",
  "const_str"
  };
}

