
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int TIPO_INTEGER = 8;
  public static final int DISPLAY = 39;
  public static final int ENDDEF = 7;
  public static final int P_C = 34;
  public static final int P_A = 33;
  public static final int OP_MAYOR = 25;
  public static final int DOS_PUNTOS = 36;
  public static final int OP_NOT = 15;
  public static final int OP_AND = 13;
  public static final int OP_ASIG_RES = 28;
  public static final int OP_DIV = 20;
  public static final int GET = 38;
  public static final int OP_MUL = 19;
  public static final int CONST_FLOAT = 4;
  public static final int IF = 11;
  public static final int PUNTO_COMA = 35;
  public static final int ID = 2;
  public static final int EOF = 0;
  public static final int OP_ASIG_DIV = 30;
  public static final int error = 1;
  public static final int COMA = 37;
  public static final int OP_OR = 14;
  public static final int OP_RESTA = 18;
  public static final int OP_DISTINTO = 22;
  public static final int OP_ASIG_MUL = 29;
  public static final int OP_MAYOR_IGUAL = 26;
  public static final int LL_C = 32;
  public static final int LL_A = 31;
  public static final int ELSE = 12;
  public static final int OP_IGUAL = 21;
  public static final int WHILE = 10;
  public static final int OP_MENOR_IGUAL = 24;
  public static final int TIPO_FLOAT = 9;
  public static final int DEFVAR = 6;
  public static final int CONST_STR = 5;
  public static final int OP_SUMA = 17;
  public static final int OP_ASIG_SUM = 27;
  public static final int OP_ASIG = 16;
  public static final int OP_MENOR = 23;
  public static final int CONST_INT = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "CONST_INT",
  "CONST_FLOAT",
  "CONST_STR",
  "DEFVAR",
  "ENDDEF",
  "TIPO_INTEGER",
  "TIPO_FLOAT",
  "WHILE",
  "IF",
  "ELSE",
  "OP_AND",
  "OP_OR",
  "OP_NOT",
  "OP_ASIG",
  "OP_SUMA",
  "OP_RESTA",
  "OP_MUL",
  "OP_DIV",
  "OP_IGUAL",
  "OP_DISTINTO",
  "OP_MENOR",
  "OP_MENOR_IGUAL",
  "OP_MAYOR",
  "OP_MAYOR_IGUAL",
  "OP_ASIG_SUM",
  "OP_ASIG_RES",
  "OP_ASIG_MUL",
  "OP_ASIG_DIV",
  "LL_A",
  "LL_C",
  "P_A",
  "P_C",
  "PUNTO_COMA",
  "DOS_PUNTOS",
  "COMA",
  "GET",
  "DISPLAY"
  };
}

